#!/usr/bin/env python3
"""Package maturity registry — single machine-readable source (MAT-01..04).

docs/package-maturity.yml is the ONLY place package maturity is maintained.
This tool:

1.  MAT-01  validates the registry: unique (repo, package) pairs, known
            maturity/contract values, and every repo present in
            docs/project-index.json.
2.  MAT-03  enforces: maturity stable requires contract stable.
3.  MAT-04  refuses to emit production-recommendation wording for any package
            that is not stable (research/beta/alpha packages are never
            "recommended for production").
4.  MAT-02  regenerates docs/package-maturity.md; with --check it exits 1 when
            the generated file drifts from the registry.

Exit 0 on success. Requires PyYAML (installed in CI).
"""

from __future__ import annotations

import json
import os
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRY_PATH = os.path.join(REPO_ROOT, "docs", "package-maturity.yml")
INDEX_PATH = os.path.join(REPO_ROOT, "docs", "project-index.json")
PAGE_PATH = os.path.join(REPO_ROOT, "docs", "package-maturity.md")

MATURITIES = {"stable", "beta", "alpha", "experimental", "research"}
CONTRACTS = {"stable", "evolving", "unstable"}


def main() -> int:
    check_mode = "--check" in sys.argv
    registry = yaml.safe_load(open(REGISTRY_PATH, encoding="utf-8"))
    packages = registry.get("packages") or []
    index = json.load(open(INDEX_PATH, encoding="utf-8"))
    index_repos = {repo.get("name") for repo in index.get("repos", [])}

    failures: list[str] = []
    seen: set[tuple[str, str]] = set()
    for entry in packages:
        repo = entry.get("repo")
        package = entry.get("package")
        maturity = entry.get("maturity")
        contract = entry.get("contract")
        key = (repo, package)
        if key in seen:
            failures.append(f"MAT-01: duplicate package entry {repo}/{package}")
        seen.add(key)

        if repo not in index_repos:
            failures.append(f"MAT-01: repo '{repo}' is not present in docs/project-index.json")
        if maturity not in MATURITIES:
            failures.append(f"MAT-01: {repo}/{package}: unknown maturity '{maturity}'")
        if contract not in CONTRACTS:
            failures.append(f"MAT-01: {repo}/{package}: unknown contract '{contract}'")

        if maturity == "stable" and contract != "stable":
            failures.append(f"MAT-03: {repo}/{package}: maturity stable requires contract stable")

    # --- generate the human page ---
    rows = []
    for entry in sorted(packages, key=lambda e: (e["repo"], e["package"])):
        production_note = (
            "Yes (documented limitations apply)" if entry["maturity"] == "stable" else "No"
        )
        rows.append(
            f"| `{entry['package']}` | `{entry['repo']}` | {entry['maturity']} | "
            f"{entry['contract']} | {production_note} |"
        )
        # MAT-04: non-stable packages must never be production-recommended.
        if entry["maturity"] != "stable" and "production" in production_note.lower():
            failures.append(f"MAT-04: {repo}/{package}: non-stable package emitted production wording")

    page = "\n".join(
        [
            "# Package Maturity",
            "",
            "Generated from [`docs/package-maturity.yml`](package-maturity.yml) — the single",
            "machine-readable source. Do not edit this file directly; run",
            "`python scripts/generate-package-maturity.py` and commit.",
            "",
            "| Package | Repository | Maturity | Contract | Recommended for production |",
            "|---|---|---|---|---|",
            *rows,
            "",
            "Maturity meanings follow [`docs/maturity-matrix.md`](maturity-matrix.md):",
            "only `stable` packages are recommended for production; `beta`/`alpha`/",
            "`experimental`/`research` packages carry no production recommendation.",
            "",
        ]
    )

    if check_mode:
        current = open(PAGE_PATH, encoding="utf-8").read() if os.path.isfile(PAGE_PATH) else ""
        if current != page:
            failures.append("MAT-02: docs/package-maturity.md drifted from the registry — regenerate")
    else:
        with open(PAGE_PATH, "w", encoding="utf-8") as handle:
            handle.write(page)

    if failures:
        for failure in failures:
            print(f"FAIL {failure}")
        print(f"\npackage-maturity: {len(failures)} failure(s)")
        return 1

    print(f"package-maturity: OK ({len(packages)} package(s)){'; page regenerated' if not check_mode else ''}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
